vich_uploader:
    db_driver: orm

    mappings:
        projects:
            uri_prefix: /img/upload/projects
            upload_destination: '%kernel.project_dir%/public/img/upload/projects'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        markers:
            uri_prefix: /img/upload/markers
            upload_destination: '%kernel.project_dir%/public/img/upload/markers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer